# Generated by Django 4.0.4 on 2022-05-03 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 9, 46, 15, 310953, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmed'), ('pr', 'In progress'), ('com', 'Completed'), ('can', 'Canceled')], default='p', help_text='Status', max_length=3),
        ),
    ]
