# Generated by Django 4.0.4 on 2022-05-03 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_order_order_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 12, 53, 11, 258173, tzinfo=utc), verbose_name='Order Date'),
        ),
    ]
