# Generated by Django 4.0.4 on 2022-05-05 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 9, 16, 43, 569558, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='orderingline',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line', to='autoservice.order', verbose_name='Order'),
        ),
    ]
