# Generated by Django 4.0.4 on 2022-05-05 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='cars_image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 11, 34, 44, 653901, tzinfo=utc), verbose_name='Order Date'),
        ),
    ]
