# Generated by Django 4.0.4 on 2022-05-05 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_car_image_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 54, 35, 838485, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(null=True, verbose_name='Price'),
        ),
    ]
