# Generated by Django 4.0.4 on 2022-05-10 07:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0007_alter_order_order_date_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Return time'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 32, 58, 192367, tzinfo=utc), verbose_name='Order Date'),
        ),
    ]
