# Generated by Django 4.0.4 on 2022-05-10 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_order_return_time_order_user_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 12, 11, 40, 36667, tzinfo=utc), verbose_name='Order Date'),
        ),
    ]
