# Generated by Django 4.0.4 on 2022-05-19 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0020_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 40, 0, 295005, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_time',
            field=models.DateField(blank=True, null=True, verbose_name='Return time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('con', 'Confirmed'), ('pr', 'In progress'), ('com', 'Completed'), ('can', 'Canceled')], default='con', help_text='Status', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='ordersreview',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Rewiews'),
        ),
        migrations.AlterField(
            model_name='ordersreview',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 11, 40, 0, 297000, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='ordersreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='autoservice.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='ordersreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
