# Generated by Django 4.0.4 on 2022-05-23 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0023_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersreview',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 9, 48, 47, 187232, tzinfo=utc), verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='ordersreview',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 9, 48, 47, 191226, tzinfo=utc), verbose_name='Order Date'),
        ),
    ]
